version: "3"
services:
  cron-backup-cron:
    image: cron-backup
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/backup/data
      - ./config:/config
    environment:
      - CRON_SCHEDULE=0 2 * * *           # 每天凌晨2点备份
      - RCLONE_REMOTE_NAMES=backup
      - RCLONE_backup_TYPE=s3
      - RCLONE_backup_ACCESS_KEY_ID=你的Key
      - RCLONE_backup_SECRET_ACCESS_KEY=你的Secret
      - RCLONE_backup_REGION=你的Region
      - LOG_TARGET=console                 # 日志输出到控制台
      - UID=1000                         # 容器内运行用户UID
      - GID=1000                         # 容器内运行用户GID

  cron-backup-loop:
    image: cron-backup
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data:/backup/data
      - ./config:/config
    environment:
      - INTERVAL_SECONDS=3600            # 每小时循环备份
      - RCLONE_REMOTE_NAMES=backup
      - RCLONE_backup_TYPE=sftp
      - RCLONE_backup_HOST=example.com
      - RCLONE_backup_USER=username
      - RCLONE_backup_PASS=password
      - LOG_TARGET=file                  # 日志写入文件
      - UID=1000
      - GID=1000

  cron-backup-once:
    image: cron-backup
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/backup/data
      - ./config:/config
    environment:
      - RCLONE_REMOTE_NAMES=backup
      - RCLONE_backup_TYPE=drive
      - RCLONE_backup_CLIENT_ID=xxx
      - RCLONE_backup_CLIENT_SECRET=yyy
      - RCLONE_backup_TOKEN=zzz
      - LOG_TARGET=console
      - UID=1000
      - GID=1000
    command: ["/backup/backup.sh"]   # 只执行一次备份
