version: "3"
services:
    corn-backup:
        restart: always
        image: cron-backup
        build:
            context: ./
            dockerfile: Dockerfile
        shm_size: 256mb
        volumes:
            - ./data:/backup/data
        environment:
            - ACCESS_KEY_ID=123456
